myclient/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    path('', views.index, name='index'),
    path('pojistenci/vyhledat/', views.vyhledat_pojistence, name='vyhledat_pojistence'),
    path('pojistenci/vytvor/', views.vytvor_pojistence, name='vytvor_pojistence'),
    path('vysledky_vyhledavani/', views.vysledky_vyhledavani, name='vysledky_vyhledavani'),
    path('myclient/', views.login_view, name='login'),
    path('smazat_pojistence/<int:cislo_pojistence>/', views.smazat_pojistence, name='smazat_pojistence'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('admin/', admin.site.urls),
    path('vytvor_bydliste_pro_klienta/<int:pojistenec_id>/', views.vytvor_bydliste_pro_klienta, name='vytvor_bydliste_pro_klienta'),
    path('vytvor_smlouvy/<int:pojistenec_id>/', views.vytvor_smlouvu, name='vytvor_smlouvy'),
    path('narozeniny_dnes/', views.narozeniny_dnes, name='narozeniny_dnes'),
    path('vypsat_vse/', views.vypsat_vse, name='vypsat_vse'),
    path('pojistenec/<int:cislo_pojistence>/', views.detail_pojistence, name='detail_pojistence'),
    path('editovat_pojistence/<int:cislo_pojistence>/', views.editovat_pojistence, name='editovat_pojistence'),

]


pojistenciapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("myclient/", include("myclient.urls")),
]

myclient/models.py
from django.db import models
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import re


# Definuje model adresy bydliště
class Bydliste(models.Model):
    ulice = models.CharField(max_length=100)
    cislo_popisne = models.CharField(max_length=10, null=True, blank=True)
    mesto = models.CharField(max_length=100)
    psc = models.IntegerField()
    
    def __str__(self):
        return f"{self.ulice}, {self.cislo_popisne}, {self.mesto} {self.psc}"


# Validátor pro ověření správného formátu e-mailu
def validate_email_format(value):
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    if not re.match(pattern, value):
        raise ValidationError('E-mail nemá správný formát.')


# Validátor pro kontrolu, zda jméno obsahuje číslice
def validate_name(value):
    if any(char.isdigit() for char in value):
        raise ValidationError('Jméno nesmí obsahovat číslice.')


# Validátor pro ověření správného formátu čísla pojištěnce
def validate_cislo_pojistence(value):
    if not re.match(r'^\d{10}$', str(value)):
        raise ValidationError('Neplatný formát čísla pojištěnce.')


# Definuje model pojištěnce
class Pojistenci(models.Model):
    jmeno = models.CharField(max_length=100, validators=[validate_name])
    prijmeni = models.CharField(max_length=100, validators=[validate_name])
    cislo_pojistence = models.IntegerField(validators=[validate_cislo_pojistence], unique=True, error_messages={'unique': "Pojištěnec s tímto číslem již existuje."})
    datum_narozeni = models.DateField()
    telefon = models.CharField(max_length=20)
    email = models.EmailField(validators=[validate_email_format])
    bydliste = models.ForeignKey(Bydliste, on_delete=models.CASCADE, default=None, null=True)
    
    def __str__(self):
        return self.jmeno


# Validátor pro ověření správného formátu čísla smlouvy
def validate_cislo_smlouvy(value):
    if not re.match(r'^\d{9}$', str(value)):
        raise ValidationError('Číslo smlouvy musí mít 9 číslic.')


# Definuje model pojistné smlouvy
class Smlouva(models.Model):
    cislo_smlouvy = models.IntegerField(validators=[validate_cislo_smlouvy], unique=True, error_messages={'unique': "Smlouva s tímto číslem již existuje."})
    datum_pocatek = models.DateField()
    datum_vyroci = models.DateField()
    
    TYPE_CHOICES = (
        ('majetek', 'Majetek'),
        ('auto', 'Auto'),
        ('zivot', 'Život'),
        ('investice', 'Investice'),
        ('mojefirma', 'Moje Firma'),
        ('podnikatele', 'Podnikatelé'),
        ('prumysl', 'Průmysl'),
        ('drony', 'Drony'),
        ('flotila', 'Flotila'),
    )
    
    typ_smlouvy = models.CharField(max_length=20, choices=TYPE_CHOICES)
    pojistenec = models.ForeignKey(Pojistenci, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return f"Cislo smlouvy: {self.cislo_smlouvy}, Pojisteni: {self.datum_pocatek} {self.datum_vyroci} {self.typ_smlouvy}"    


# Formulář pro registraci uživatele
class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


# Formulář pro přihlášení uživatele
class LoginForm(AuthenticationForm):
    class Meta:
        fields = ('username', 'password')

myclient/forms.py
from django import forms
from .models import Pojistenci, Bydliste, Smlouva

class PojistenciForm(forms.ModelForm):
    class Meta:
        model = Pojistenci
        fields = ['jmeno', 'prijmeni', 'cislo_pojistence', 'datum_narozeni', 'telefon', 'email']

    def __init__(self, *args, **kwargs):
        super(PojistenciForm, self).__init__(*args, **kwargs)
        self.fields['jmeno'].widget.attrs.update({'class': 'form-control'})
        self.fields['prijmeni'].widget.attrs.update({'class': 'form-control'})
        self.fields['cislo_pojistence'].widget.attrs.update({'class': 'form-control'})
        self.fields['datum_narozeni'].widget.attrs.update({'class': 'form-control'})
        self.fields['telefon'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        
        
class ConfirmDeleteForm(forms.Form):
    confirm_delete = forms.BooleanField(label="Potvrďte smazání", required=False)
    
    
class BydlisteForm(forms.ModelForm):
    class Meta:
        model = Bydliste
        fields = ['ulice', 'cislo_popisne', 'mesto', 'psc']

    def __init__(self, *args, **kwargs):
        super(BydlisteForm, self).__init__(*args, **kwargs)
        self.fields['ulice'].widget.attrs.update({'class': 'form-control'})
        self.fields['cislo_popisne'].widget.attrs.update({'class': 'form-control'})
        self.fields['mesto'].widget.attrs.update({'class': 'form-control'})
        self.fields['psc'].widget.attrs.update({'class': 'form-control'})
        
class SmlouvyForm(forms.ModelForm):
    class Meta:
        model = Smlouva
        fields = ['cislo_smlouvy', 'datum_pocatek', 'datum_vyroci', 'typ_smlouvy']

    def __init__(self, *args, **kwargs):
        super(SmlouvyForm, self).__init__(*args, **kwargs)
        self.fields['cislo_smlouvy'].widget.attrs.update({'class': 'form-control'})
        self.fields['datum_pocatek'].widget.attrs.update({'class': 'form-control'})
        self.fields['datum_vyroci'].widget.attrs.update({'class': 'form-control'})
        self.fields['typ_smlouvy'].widget.attrs.update({'class': 'form-control'})
    
class VyhledatPojistenceForm(forms.Form):
    jmeno = forms.CharField(label="Jméno", required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    prijmeni = forms.CharField(label="Příjmení", required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    cislo_pojistence = forms.CharField(label="Číslo pojištěnce", required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))   
    

myclient/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Pojistenci, Smlouva, Bydliste
from .forms import PojistenciForm, ConfirmDeleteForm, BydlisteForm, SmlouvyForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from datetime import date, datetime
from django.db.models import Q
from django.db import IntegrityError, DatabaseError
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.db import transaction
import logging

logger = logging.getLogger(__name__)






@login_required
def index(request):
    """
    Zobrazuje hlavní stránku aplikace.

    Args:
        request (HttpRequest): Objekt obsahující data o HTTP požadavku.

    Returns:
        HttpResponse: Renderovaná stránka 'index.html'.
    """
    return render(request, 'index.html')



@login_required
def vyhledat_pojistence(request):
    """
    Umožňuje uživatelům vyhledat pojištěnce podle jména, příjmení nebo čísla pojistného.

    Args:
        request (HttpRequest): Objekt obsahující data o HTTP požadavku.

    Returns:
        HttpResponse: Renderovaná stránka s výsledky vyhledávání nebo vyhledávacím formulářem.
    """
    vysledky = []  # Seznam pro uložení výsledků vyhledávání.

    # Kontroluje, zda byl formulář odeslán pomocí metody POST.
    if request.method == "POST":
        # Získává hodnoty z formuláře.
        jmeno = request.POST.get('jmeno', '')
        prijmeni = request.POST.get('prijmeni', '')
        cislo_pojistence = request.POST.get('cislo_pojistence', '')

        # Vytvoříme prázdnou Q instanci.
        query = Q()

        # Přidáváme podmínky do Q objektu podle toho, jaké hodnoty byly zadané.
        if jmeno:
            query |= Q(jmeno__contains=jmeno)
        if prijmeni:
            query |= Q(prijmeni__contains=prijmeni)
        if cislo_pojistence:
            query |= Q(cislo_pojistence=cislo_pojistence)

        # Pokud byla zadána alespoň jedna hodnota, provádíme vyhledávání v databázi.
        if jmeno or prijmeni or cislo_pojistence:
            vysledky = Pojistenci.objects.select_related('bydliste').filter(query)

        # Vrací stránku s výsledky vyhledávání.
        return render(request, 'vysledky_vyhledavani.html', {'vysledky': vysledky})

    # Vrací vyhledávací formulář, pokud nebyl formulář odeslán.
    return render(request, 'vyhledat_pojistence.html')






@login_required
def vytvor_pojistence(request):
    """
    Tato funkce zobrazuje a zpracovává formulář pro vytvoření nového pojistníka.
    Pokud je metoda požadavku POST a formulář je platný, uloží nového pojistníka do databáze 
    a přesměruje uživatele k dalšímu kroku - vytvoření bydliště pro tohoto pojistníka.
    """
    if request.method == "POST":
        form = PojistenciForm(request.POST)
        if form.is_valid():
            try:
                pojistenec = form.save()
                return redirect('vytvor_bydliste_pro_klienta', pojistenec_id=pojistenec.id)
            
            except IntegrityError:
                # Chyba spojená s omezeními integrity databáze.
                messages.error(request, 'Došlo k chybě při ukládání pojistníka. Zkuste to znovu.')
            
                       
            except DatabaseError:
                # Obecná chyba databáze.
                messages.error(request, 'Došlo k chybě databáze. Kontaktujte správce.')
            
            
    else:
        form = PojistenciForm()

    return render(request, 'vytvor_pojistence.html', {'form': form})


    
    



def vytvor_bydliste_pro_klienta(request, pojistenec_id):
    """
    Tato funkce zobrazuje a zpracovává formulář pro vytvoření bydliště pro zadaného pojistníka.
    Pokud je metoda požadavku POST a formulář je platný, uloží nové bydliště do databáze 
    a přiřadí je k danému pojistníkovi.
    """
    # Získání pojistníka podle zadaného ID.
    try:
        pojistenec = Pojistenci.objects.get(id=pojistenec_id)
    except Pojistenci.DoesNotExist:
        messages.error(request, 'Pojistenec nebyl nalezen.')
        return redirect('index')  # Přesměrujte na vhodnou chybovou stránku nebo na úvodní stránku.

    if request.method == "POST":
        bydliste_form = BydlisteForm(request.POST)  # Načtení dat z odeslaného formuláře.
        if bydliste_form.is_valid():
            try:
                bydliste = bydliste_form.save()  # Uložení nového bydliště do databáze.
                pojistenec.bydliste = bydliste  # Přiřazení nového bydliště k pojistníkovi.
                pojistenec.save()  # Uložení aktualizovaného pojistníka do databáze.
                return redirect('vytvor_smlouvy', pojistenec_id=pojistenec.id)  # Přesměrování uživatele.
            except IntegrityError:
                messages.error(request, 'Došlo k chybě integrity. Zkontrolujte zadané údaje a zkuste to znovu.')
            except DatabaseError:
                messages.error(request, 'Došlo k problému s databází. Zkuste to prosím později.')
    else:
        bydliste_form = BydlisteForm()  # Inicializace prázdného formuláře pro vytvoření bydliště.
    
    return render(request, 'vytvor_bydliste_pro_klienta.html', {'klient': pojistenec, 'bydliste_form': bydliste_form})







def vytvor_smlouvu(request, pojistenec_id):
    try:
        # Získání pojištěnce podle ID
        pojistenec = Pojistenci.objects.get(id=pojistenec_id)
    except Pojistenci.DoesNotExist:
        messages.error(request, 'Pojištěnec nebyl nalezen.')
        return redirect('index')  # Přesměrujte na vhodnou chybovou stránku nebo na úvodní stránku.

    # Inicializace prázdného formuláře
    smlouva_form = SmlouvyForm()

    if request.method == "POST":
        # Zpracování formuláře pro vytvoření smlouvy
        smlouva_form = SmlouvyForm(request.POST)
        if smlouva_form.is_valid():
            try:
                # Začátek transakce
                with transaction.atomic():
                    # Vytvoření instance smlouvy, ale neukládání do databáze (commit=False)
                    smlouva = smlouva_form.save(commit=False)
                    # Přiřazení pojištěnce k smlouvě
                    smlouva.pojistenec = pojistenec
                    # Uložení smlouvy do databáze
                    smlouva.save()
                    # Získání akce z formuláře
                    action = request.POST.get("action")
                    if action == "opakovat":
                        # Pokud je vybráno opakování, přesměrovat zpět na stejnou stránku
                        return redirect('vytvor_smlouvy', pojistenec_id=pojistenec_id)
                    else:
                        # Jinak přesměrovat na hlavní stránku
                        return redirect('index')
            except IntegrityError:
                messages.error(request, 'Došlo k chybě integrity. Zkontrolujte zadané údaje a zkuste to znovu.')
            except DatabaseError:
                messages.error(request, 'Došlo k problému s databází. Zkuste to prosím později.')
        else:
            # Vypíše chyby formuláře, pokud není platný
            print(smlouva_form.errors)

    return render(request, 'vytvor_smlouvy.html', {'klient': pojistenec, 'smlouva_form': smlouva_form})





@login_required
def vysledky_vyhledavani(request):
    """
    Zpracování vyhledávání pojištěnců na základě zadaného jména, příjmení nebo čísla pojištěnce.
    
    Pokud je metoda požadavku POST, filtruje databázi pojištěnců podle zadaných kritérií.
    Výsledky vyhledávání obsahují i informace o bydlišti pojištěnce a smlouvách, které má uzavřené.
    """
    
    if request.method == "POST":
        # Získání dat z formuláře.
        jmeno = request.POST.get('jmeno')
        prijmeni = request.POST.get('prijmeni')
        cislo_pojistence = request.POST.get('cislo_pojistence')
        
        # Filtrace databáze pojištěnců na základě zadaných kritérií.
        vysledky = Pojistenci.objects.select_related('bydliste').prefetch_related('smlouva').filter(
            jmeno__contains=jmeno, 
            prijmeni__contains=prijmeni, 
            cislo_pojistence=cislo_pojistence
        )

        return render(request, 'vysledky_vyhledavani.html', {'vysledky': vysledky})

    # Pokud není metoda POST, zobrazí se stránka pro vyhledávání.
    return render(request, 'vysledky_vyhledavani.html')  

def login_view(request):
    """
    Zobrazení a zpracování přihlašovacího formuláře.

    Pokud je metoda požadavku POST a přihlašovací údaje jsou správné, uživatel je přihlášen a přesměrován na indexovou stránku.
    Pokud údaje nejsou správné, zobrazí se chybová zpráva.
    Pokud je metoda jiná než POST, zobrazí se přihlašovací formulář.
    """
    
    if request.method == 'POST':
        # Zpracování odeslaného přihlašovacího formuláře.
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')  

    else:
        # Pokud není metoda POST, zobrazí se přihlašovací formulář.
        form = AuthenticationForm()

    return render(request, 'index.html', {'form': form})



@login_required
def smazat_pojistence(request, cislo_pojistence):
    """
    Funkce umožňuje uživateli smazat pojištěnce na základě čísla pojištěnce.
    

myclient/templates/myclient/editovat_pojistence.html
{% load static %}

<!DOCTYPE html>
<html lang="cs">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editovat pojištěnce</title>
    <link rel="stylesheet" href="{% static 'myclient/formulare.css' %}">
</head>

<body>
    <div class="container">
        <h1>Editovat pojištěnce</h1>

            <form method="post">
            {% csrf_token %}
            
            <!-- Sekce pro vložení jména -->
            <label for="jmeno">Jméno:</label>
            <input type="text" id="jmeno" name="jmeno" value="{{ pojistenec.jmeno }}" required class="{{ form.jmeno.field.widget.attrs.class }}">
            {% if form.jmeno.errors %}
                <span class="error">{{ form.jmeno.errors.0 }}</span>
            {% endif %}

            <!-- Sekce pro vložení příjmení -->
            <label for="prijmeni">Příjmení:</label>
            <input type="text" id="prijmeni" name="prijmeni" value="{{ pojistenec.prijmeni }}" required class="{{ form.prijmeni.field.widget.attrs.class }}">
            {% if form.prijmeni.errors %}
                <span class="error">{{ form.prijmeni.errors.0 }}</span>
            {% endif %}

            <!-- Sekce pro vložení čísla pojištěnce (bez editace) -->
            <label for="cislo_pojistence">Číslo pojištěnce - neměnný údaj!:</label>
            <input type="text" id="cislo_pojistence" name="cislo_pojistence" value="{{ pojistenec.cislo_pojistence }}" readonly class="{{ form.cislo_pojistence.field.widget.attrs.class }}">

            <!-- Sekce pro vložení data narození -->
            <label for="datum_narozeni">Datum narození:</label>
            <input type="date" id="datum_narozeni" name="datum_narozeni" value="{{ pojistenec.datum_narozeni|date:'Y-m-d' }}" required class="{{ form.datum_narozeni.field.widget.attrs.class }}">
            {% if form.datum_narozeni.errors %}
                <span class="error">{{ form.datum_narozeni.errors.0 }}</span>
            {% endif %}

            <!-- Sekce pro vložení telefonního čísla -->
            <label for="telefon">Telefon:</label>
            <input type="text" id="telefon" name="telefon" value="{{ pojistenec.telefon }}" required class="{{ form.telefon.field.widget.attrs.class }}">
            {% if form.telefon.errors %}
                <span class="error">{{ form.telefon.errors.0 }}</span>
            {% endif %}

            <!-- Sekce pro vložení emailové adresy -->
            <label for="email">Email:</label>
            <input type="text" id="email" name="email" value="{{ pojistenec.email }}" required class="{{ form.email.field.widget.attrs.class }}">
            {% if form.email.errors %}
                <span class="error">{{ form.email.errors.0 }}</span>
            {% endif %}

            

            <!-- Tlačítko pro odeslání formuláře -->
            <button type="submit">Uložit změny</button>
        </form>
        
        <a href="{% url 'index' %}">Zpět na úvodní stránku</a>
    </div>

    <!-- Logo aplikace -->
    <img src="{% static 'myclient/images/logo_aplikace.png' %}" alt="Logo" class="logo-img">
</body>

</html>

myclient/templates/myclient/index.html
{% load static %}
{% load i18n %}

<!-- Základní HTML struktura -->
<!DOCTYPE html>
<html lang="cs">
<head>
    <!-- Metadata o stránce -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Správa pojištěnců</title>
    <!-- Odkaz na CSS styly pro tuto stránku -->
    <link rel="stylesheet" href="{% static 'myclient/style.css' %}">
</head>
<body>
    <!-- Hlavní obsah stránky -->
    <div class="main-content">
        <!-- Sekce s názvem aplikace -->
        <div class="content">
            <h1>MyClient</h1>
        </div>
    
        <!-- Sekce s navigačním panelem -->
        <div class="container">
            <div class="navbar">
                <ul>
                    <!-- Navigační odkazy -->
                    <li><a href="{% url 'vyhledat_pojistence' %}" class="button">Vyhledej pojištěnce</a></li>
                    <li><a href="{% url 'vytvor_pojistence' %}" class="button">Přidej pojištěnce</a></li>
                    <li><a href="{% url 'vypsat_vse' %}" class="button">Všichni pojištěnci</a></li>
                    <li><a href="outlookcal://" class="button">Kalendář</a></li>
                    <!-- Podmínka pro zobrazení administračního odkazu -->
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'admin:index' %}" class="button">Admin</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
            
        <!-- Sekce s přihlašováním -->
        <div class="container1">
            <div class="login-form">
                <!-- Zobrazuje aktuální datum -->
                <p style="float: left; margin-top: 20px; margin-left: 20px; color: white; font-size: 1.2em;">Dnešní datum: {% now "d. m. Y" %}</p>
                <!-- Podmínka pro kontrolu, zda je uživatel přihlášen -->
                {% if user.is_authenticated %}
                    <div class="user-name">
                        <!-- Zobrazuje jméno přihlášeného uživatele -->
                        <p style="margin-right: 15px; color: white; font-size: 1.2em;float: left">
                            Vítejte, {{ user.first_name }}!</p>
                        <a href="{% url 'logout' %}" class="button1">Odhlásit se</a>
                    </div>
                {% else %}
                    <!-- Formulář pro přihlášení -->
                    <form method="post" action="{% url 'login' %}">
                        {% csrf_token %}
                        {{ form.username.label_tag }}
                        {{ form.username }}
                        {{ form.password.label_tag }}
                        {{ form.password }}
                        
                        <button type="submit" class="button1">Přihlásit se</button>
                        <p>Nejste přihlášen/a.</p>
                    </form><br>
                {% endif %}
            </div>
        </div>

        <!-- Sekce s odkazem na narozeniny -->
        <div class="container-narozeniny">
            <a href="{% url 'narozeniny_dnes' %}" class="button">Narozeniny dnes</a>
            {% include 'narozeniny_dnes.html' %}
        </div>
    
        <!-- Logo aplikace -->
        <div class="logo">
            <img src="{% static 'myclient/images/logo_aplikace.png' %}" alt="Logo" width="100" height="100">
        </div>
    </div>

    <!-- Patička stránky -->
    <footer>
        Vytvořil &copy; Lukáš Svoboda 2023
    </footer>
</body>
</html>

myclient/templates/myclient/narozeniny_dnes.html
<!-- Tento kód je jednoduchý HTML dokument, který zobrazuje seznam pojištěnců, kteří mají dnes narozeniny. 
    Pokud žádný pojištěnec narozeniny nemá, zobrazí se výpis, že žádní pojištěnci dnes narozeniny nemají. -->


{% load static %} <!-- Načítání statických souborů pro Django -->

<!DOCTYPE html>
<html>

<head>
    <title>Pojištěnci s narozeninami dnes</title>
    
    <!-- Připojení externího CSS souboru -->
    <link rel="stylesheet" href="{% static 'myclient/narozeniny.css' %}">
</head>

<body>

    <!-- Nadpis sekce -->
    <h2>Dnes má narozeniny</h2>
    
    <!-- Seznam pojištěnců s narozeninami dnes -->
    <ul>
        <!-- Iterace přes seznam pojištěnců a jejich věk -->
        {% for pojistenec, vek in pojistenci_a_vek %}
            <li>
                <!-- Zobrazí jméno a příjmení pojištěnce -->
                <span class="name">{{ pojistenec.jmeno }} {{ pojistenec.prijmeni }}</span>
                
                <!-- Zobrazí aktuální věk pojištěnce -->
                {{ vek }} let
                
                <!-- Zobrazí telefonní číslo pojištěnce -->
                <span class="telefon">telefon: {{ pojistenec.telefon }}</span>
            </li>
            
        {% empty %} <!-- Podmínka, pokud nejsou žádní pojištěnci s narozeninami dnes -->
            <li>Žádní pojištěnci dnes narozeniny nemají.</li>
        {% endfor %}
    </ul>

</body>
</html>

myclient/templates/myclient/vysledky_vyhledavani.html
{% load static %} 
<!DOCTYPE html>
<html lang="cs">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Výsledky vyhledávání</title>
    <link rel="stylesheet" href="{% static 'myclient/vyhledavani.css' %}">
</head>

<body>
    <div class="container">
        {% if vysledky.count == 0 %}
            <h2>Nic nenalezeno</h2>
        {% else %}
            <h1>Výsledky vyhledávání</h1>
            
            {% for vysledek in vysledky %}
                <h2>Pojištěnec</h2>
                <table class="results-table">
                    <tr>
                        <td>
                            <div class="info1">
                                <strong>Jméno:</strong><br>
                                <strong>Číslo pojištěnce:</strong><br>
                                <strong>Datum narození:</strong><br>
                                <strong>Telefon:</strong><br>
                                <strong>Email:</strong><br>
                                <strong>Adresa:</strong><br>
                            </div>
                        </td>
                        <td>
                            <div class="info1">
                                {{ vysledek.jmeno }} {{ vysledek.prijmeni }}<br>
                                {{ vysledek.cislo_pojistence }}<br>
                                {{ vysledek.datum_narozeni }}<br>
                                {{ vysledek.telefon }}<br>
                                {{ vysledek.email }}<br>
                                {{ vysledek.bydliste.ulice }} {{ vysledek.bydliste.cislo_popisne }}, {{ vysledek.bydliste.mesto }} {{ vysledek.bydliste.psc }}<br>
                            </div>
                        </td>
                    </tr>
                    
                    <tr>
                        <td colspan="2">
                            <div class="info">
                                <h2>Smlouvy</h2>
                            </div>
                            <table class="smlouvy">
                                <tr>
                                    <th>Číslo smlouvy</th>
                                    <th>Datum počátku</th>
                                    <th>Datum výročí</th>
                                    <th>Typ smlouvy</th>
                                </tr>
                                {% for smlouva in vysledek.smlouva_set.all %}
                                    <tr>
                                        <td>{{ smlouva.cislo_smlouvy }}</td>
                                        <td>{{ smlouva.datum_pocatek }}</td>
                                        <td>{{ smlouva.datum_vyroci }}</td>
                                        <td>{{ smlouva.get_typ_smlouvy_display }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </td>
                    </tr>

                    <tr>
                        <form method="post" action="{% url 'editovat_pojistence' vysledek.cislo_pojistence %}">
                            {% csrf_token %}
                            <td><button type="submit">Editovat pojištěnce</button></td>
                        </form>
                        <form method="post" action="{% url 'smazat_pojistence' vysledek.cislo_pojistence %}">
                            {% csrf_token %}
                            <td><button type="submit">Smazat pojištěnce</button></td>
                        </form>
                    </tr>
                </table>
                
                {% if not forloop.last %}
                    <hr class="vysledek-separator">
                {% endif %}
            {% endfor %}
        {% endif %}
        
        <a href="{% url 'index' %}">Zpět na úvodní stránku</a>
    </div>

    <img src="/static/myclient/images/logo_aplikace.png" alt="Logo" class="logo-img">
</body>
</html>